name: build-shelly-homekit
on:
 push:
 pull_request:
jobs:
 build:
   name: Build ${{ matrix.model }}
   runs-on: ubuntu-latest
   strategy:
     fail-fast: false
     matrix:
       model:
         - Shelly1Gen3
   steps:
     - name: Checkout code
       uses: actions/checkout@v4
       with:
         fetch-depth: 0
     - name: Install mos
       run: |
          sudo curl -fsSL https://mongoose-os.com/downloads/mos/install.sh | /bin/bash
          which mos || find / -name mos -type f 2>/dev/null | head -5
          ls ~/mos_latest/ 2>/dev/null || true
          ls /usr/local/bin/mos 2>/dev/null || true
     - name: Build
       run: |
         git config --global --add safe.directory $GITHUB_WORKSPACE
         make ${{ matrix.model }} LOCAL=1 RELEASE=1 RELEASE_SUFFIX=custom
       working-directory: ${{ github.workspace }}
     - name: Upload firmware artifacts
       uses: actions/upload-artifact@v4
       with:
         name: release-${{ matrix.model }}
         path: releases/**/shelly-homekit-${{ matrix.model }}.zip
         if-no-files-found: warn
 merge:
   needs: build
   runs-on: ubuntu-latest
   steps:
     - name: Merge Artifacts
       uses: actions/upload-artifact/merge@v4
       with:
         name: all-releases
         pattern: release-*
